name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: "Features"
    labels:
      - enhancement
  - title: "Bug fixes"
    labels:
      - bug
  - title: "Dependencies"
    labels:
      - dependencies
      - github_actions
  - title: "Documentation"
    labels:
      - documentation

exclude-labels:
  - skip-changelog

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["enhancement", "feature"]
  patch:
    labels: ["bug", "dependencies", "documentation", "github_actions"]
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "**/*.md"
  - label: "github_actions"
    files:
      - ".github/**"
  - label: "dependencies"
    files:
      - "package.json"
      - "package-lock.json"
