name: Stale

on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 1"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639
        with:
          days-before-stale: 45
          days-before-close: 14
          stale-issue-message: "Marked stale due to inactivity. Reply or update to keep open."
          stale-pr-message: "Marked stale due to inactivity. Push commit or reply to keep open."
          exempt-issue-labels: "security,pinned"
          exempt-pr-labels: "security,pinned"
